- base/src/world/mod.rs
- base/src/world/provider.rs
- base/src/world/world.rs
add type PillarIndex
add chunk_at
add chunk_from_pillar
> implement more indexing methods for `World`

- base/src/math/dimension.rs
// assert!(self.height.Zero::is_zero())
doesnt work now :(
> Partial Dimension.rs

- client/src/game.rs
> Fix VRAM calculation to compile on 32-bit

- base/src/gen/mod.rs
- base/src/world/world.rs
- client/src/game.rs
- plantex/main.rs
> generate 9 dummy chunks using WorldGenerator

- base/src/world/mod.rs
- client/src/camera.rs
- client/src/game.rs
- client/src/render/mod.rs
- client/src/world/chunk.rs
- client/src/world/chunk_std.frag
- client/src/world/chunk_std.vert
- client/src/world/pillar.rs
Closes #18 
Implemented the rendering of all Hexagons per Chunk.
ToDo:
- Pillartransformation (scalevalue, translation)
> Implement World Rendering

- base/src/math/axial_vector.rs
> AxialVector

- client/src/render/to_arr.rs
> Add to_arr

- client/src/camera.rs
- client/src/event_manager.rs
- client/src/game.rs
- client/src/ghost.rs
- client/src/lib.rs
work in progress
Camera only has essential methods
> Camera and Event Handler

- base/src/prop/plant.rs
- client/src/world/chunk.rs
- client/src/world/mod.rs
- client/src/world/plant_dummy.frag
- client/src/world/plant_dummy.vert
- client/src/world/plant_view.rs
>  Rendering of the dummy plant on every hex-pillar

- base/src/world/chunk.rs
> Add get method to chunk.rs

- base/src/gen/world/mod.rs
- base/src/world/chunk.rs
- base/src/world/hex_pillar.rs
- base/src/world/world.rs
- client/src/game.rs
additionally creates a few utility methods.
> generate a simple sin-world

- base/src/math/axial_point.rs
> AxialPoint

- base/src/gen/world/mod.rs
- client/src/game.rs
> create an actual world

- base/src/world/ground.rs
- client/src/world/chunk.rs
- client/src/world/chunk_std.frag
- client/src/world/chunk_std.vert
- client/src/world/mod.rs
> Implement Material-Color

- client/src/game.rs
- client/src/lib.rs
- plantex/main.rs
This is a prerequisite for multiplayer and dynamic chunk (un-)loading (or at least it makes both much easier)
> Refactor game::run into a Game struct

- client/src/world/chunk_std.frag
- client/src/world/plant_dummy.frag
> Fix shaders on Intel GPUs

- client/src/game.rs
- client/src/ghost.rs
delta now is paramter for update function of ghost
delta will now influence the speed of the player, so the player still moves with sufficient speed, even though the game might have low FPS
> Implement Delta

- client/src/game.rs
- client/src/world/world_view.rs
- client/src/world_manager.rs
> Dynamic chunk lagging

- Cargo.lock
- base/Cargo.toml
- base/src/gen/world/mod.rs
- base/src/lib.rs
- base/src/world/chunk.rs
> add terrain generation with open simplex noise

- base/src/world/chunk.rs
- client/src/world/chunk_view.rs
> Iterator for HexPillars in Chunk

- base/src/gen/plant/tree.rs
- base/src/gen/world/mod.rs
Generate fewer trees in worldgen, generate fewer vertices per tree in treegen.
> Fewer and faster trees

- Cargo.lock
- base/Cargo.toml
- base/src/lib.rs
- base/src/msg.rs
- client/src/game.rs
- client/src/lib.rs
- client/src/renderer.rs
- plantex-server/main.rs
- plantex/main.rs
- server/Cargo.toml
- server/src/lib.rs
- server/src/server.rs
This adds a dummy server, starts it with the client, and connects to it.
> Server preparations

- base/src/gen/world/mod.rs
Creates extremely interesting terrain
> Use 3D-noise for terrain generation

- base/src/gen/mod.rs
- client/src/view/plant_dummy.frag
- client/src/view/plant_dummy.vert
- client/src/view/plant_view.rs
- client/src/world/chunk_std.frag
Plants can be rendered
Sticks are rendered correctly
> Implement Plantrendering

- client/src/renderer.rs
- client/src/tonemapping.frag
including exposure levels (handy for day night cycle) and gamma values.
part of #38
> implementation of basic tonemapping 

- client/src/game.rs
> Use config params for context creation (#69)

- base/src/gen/plant/mod.rs
- base/src/gen/plant/tree.rs
- base/src/prop/plant.rs
- client/src/view/plant_view.rs
These are currently randomly selected. We should add biome information (such as a temperature and humidity range in which the trees are able to grow) and select them based on the biome when #103 lands.
Also gives trees proper colors.
> Add a shrub and cactus preset

- client/src/camera.rs
- client/src/daytime.rs
new_from_vector returns a camera based on a position and a vector to look at
> add new_from_vector function to camera for the "shadow-group"

- Cargo.lock
- client/Cargo.toml
- client/shader/weather.frag
- client/shader/weather.vert
- client/src/game.rs
- client/src/lib.rs
- client/src/renderer.rs
- client/src/weather/mod.rs
> add weather effects

- client/shader/skydome.frag
- client/shader/skydome.vert
- client/shader/sun.frag
- client/src/game.rs
- client/src/view/sky_view.rs
call update for sky_view in gameloop
> add update fn to sky_view with sun_position

- base/src/gen/world/mod.rs
- base/src/world/chunk.rs
- base/src/world/world.rs
- client/src/control_switcher.rs
- client/src/game.rs
- client/src/ghost.rs
- client/src/lib.rs
- client/src/player.rs
> Add player physics

- Cargo.lock
- client/Cargo.toml
- client/shader/chunk_shadow.frag
- client/shader/chunk_shadow.vert
- client/shader/chunk_std.frag
- client/shader/plant_shadow.frag
- client/shader/plant_shadow.vert
- client/shader/shadow_debug.frag
- client/shader/shadow_debug.vert
- client/src/camera.rs
- client/src/daytime.rs
- client/src/player.rs
- client/src/renderer.rs
- client/src/view/plant_renderer.rs
- client/src/view/plant_view.rs
- client/src/view/sky_view.rs
- client/src/view/sun_view.rs
- client/src/world/chunk_renderer.rs
- client/src/world/chunk_view.rs
- client/src/world/world_view.rs
Plants are not yet affected by shadows (but they *do* cast shadows). We'll do that later, after we wrote a fragment shader we like.
> Basic world shadowing

- client/shader/adaption_shrink.frag
- client/shader/adaption_shrink.vert
- client/shader/bloom_blending.frag
- client/shader/sun.frag
- client/src/renderer.rs
Calculation of average brightness is implemented.
The next step is to reasonably change the exposure level.
Fixes #120
> (WIP) Most basic dynamic exposure compensation

- client/shader/chunk_std.frag
- client/shader/chunk_std.vert
- client/shader/plants.frag
- client/shader/plants.tes
- client/src/view/plant_view.rs
- client/src/world/chunk_view.rs
- client/src/world/world_view.rs
> add fog for chunks and plants

- client/shader/plants.frag
- client/src/renderer.rs
> Fix lighting at night, remove debug output

- client/shader/weather.frag
- client/shader/weather.vert
- client/src/daytime.rs
- client/src/game.rs
- client/src/weather/mod.rs
changed function name get_ambient_color to get_sun_color
> DayTime function rename

- client/shader/plants.tcs
- client/shader/plants.tes
> Fixes syntax errors in shaders

- base/src/math/axial_point.rs
- client/shader/plants.frag
- client/shader/plants.tcs
- client/shader/plants.tes
- client/src/config.rs
- client/src/game.rs
- client/src/view/plant_view.rs
- client/src/world/chunk_view.rs
- client/src/world/world_view.rs
- client/src/world_manager.rs
* Tessellation tuning
* Fail at fixing #88, but add debug stuff
* Some random shadow fix
> Render chunks sorted by distance to camera

- client/src/world_manager.rs
> load more chunks again

- client/src/config.rs
- client/src/game.rs
I know we probably don't want too many command line options but this makes working with textures a lot easier...
> add a switch to turn off pillar highlighting

- client/shader/plant_shadow.vert
- client/shader/plants.tcs
- client/shader/plants_notess.frag
- client/shader/plants_notess.vert
- client/src/config.rs
- client/src/game_context.rs
- client/src/view/plant_renderer.rs
- client/src/view/plant_view.rs
I just copied most of the shader together so it works. Gonna clean up all the shader handling soon.
> Allow disabling tessellation and simplify tcs

- client/src/config.rs
Why has no one noticed this...
> Fix copy/paste error
